### PR TITLE
Fix bug on Currency field (fixed #166)

### LINKED ISSUE #166: Currency field
I found a bug, when we try to use `Currency` field (or other with `displayUsing` function applied):

```php
Flexible::make('Invoices', 'invoices')
    ->addLayout('Invoice', 'invoice', [
        Text::make('No', 'number'),
        Currency::make('Amount', 'amount')
    ]),
```

For second row it's trying to run `displayUsing` two times on value, for third three times and so on...

For now, I've creadet custom Layout class and overwrited:
```php
public function duplicateAndHydrate($key, array $attributes = [])
{
    $fields = collect($this->fields());

    return new static(
        $this->title,
        $this->name,
        $fields,
        $key,
        $attributes
    );
}
```
So it's making a new fields instances for every repeated row, so `displayUsing` is run only once.

I think it could be good idea to change layout definition from array to clousure - and execute method everytime we need it.

### PR DESCRIPTION
**Pull request by jeffreydevreede**
Customize duplicate and hydrate function so it works with Nova Currency field (tested for version 3.5.0).

### CODE REVIEW

File: src/Layouts/Layout.php [hunk 1]
```diff
@@ -215,10 +215,14 @@ public function duplicate($key)
      */
     public function duplicateAndHydrate($key, array $attributes = [])
     {
+        $fields = $this->fields();
```
Comment (voidgraphics) [inline src/Layouts/Layout.php:218]: Could this and the foreach be written more concisely as 

```php
$fields = clone $this->fields()->all();
```
and still fix the issue?

Comment (jeffreydevreede) [reply src/Layouts/Layout.php:218]: That didn't work for me, because the internal field objects didn't get cloned but they get copied with reference.

**Comment by voidgraphics** [comment]
Thanks, will be included in the next release!
